<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \SuttonSilver\CustomCheckout\Block\Adminhtml\Question\Edit\AssignProducts $block */

/** @var \SuttonSilver\CustomCheckout\Block\Adminhtml\Question\Edit\Tab\Product $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php  echo $block->getGridHtml(); ?>
<input type="hidden" name="question_products" id="in_question_products" data-form-part="suttonsilver_question_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "SuttonSilver_CustomCheckout/js/question/assign-products": {
                "selectedProducts": <?php /* @escapeNotVerified */ echo $block->getProductsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
